version: "3.7"
volumes:
  game_helper_db:
  static_value:
  media_value:

services:
  game_helper_db:
    image: postgres:13.0-alpine
    container_name: game_helper_db
    volumes:
      - game_helper_db:/var/lib/postgresql/data/
    env_file:
        - .env
    ports:
      - "5432:5432"

  backend:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - game_helper_db
    env_file:
      - .env
    ports:
      - "8000:8000"