version: "3.7"
volumes:
  game_helper_db:
  static_volume:
  media_volume:

services:
  game_helper_db:
    image: postgres:13.0-alpine
    container_name: game_helper_db
    volumes:
      - game_helper_db:/var/lib/postgresql/data/
    env_file:
        - .env.docker
    ports:
      - "5432:5432"

  backend:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - game_helper_db
    env_file:
      - .env.docker

  nginx:
    build: ./nginx-local
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - backend
    restart: always
