# Generated by Django 5.0.4 on 2024-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_file_alter_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
